### ISSUE TITLE
Screen flickering 

### ISSUE THREAD

**Issue by ankitpanwar070798** [codse/animata#153]
**Describe the bug**
In the cycle text component page screen is flickering when the text is changing 

**To Reproduce**
1. Go to 'https://animata.design/docs/text/cycle-text'
2. See error

**Expected behavior**
The screen should not flicker while the text change

**Screenshots**
![image](https://github.com/user-attachments/assets/5e3181dc-336a-4f36-a69f-119efc523b7e)

**Comment by hari** [comment]
@ankitpanwar070798 Could you share a video?

**Comment by Hackerbee** [comment]
https://github.com/user-attachments/assets/0336db68-63af-4710-92b6-5b0b0f06da9e

**Comment by ankitpanwar070798** [comment]
Hey Codse/Animata
Yeah why not but I have fix the code in local will push the code and raise
MR SOON

**Comment by hari** [comment]
Closed by #156

**Comment by ankitpanwar070798** [comment]
Awesome, thanks for the update! I would love to help you guys if needed
just let me know
