### ISSUE TITLE
Trailing Image component 

### ISSUE THREAD

**Issue by ankitpanwar070798** [codse/animata#166]
**Describe the bug**
In Trailing Image while hovering over the component, if we scroll at the end and then scroll which should not happened .

**To Reproduce**
1. Go to 'https://animata.design/docs/image/trailing-image'
2. Check the component 
3. Scroll down
![Screenshot 2024-07-23 140453](https://github.com/user-attachments/assets/4559da76-db35-4388-be81-370127b38ae3)

**Comment by hari** [comment]
@ankitpanwar070798 we have deployed a fix #167. Could you verify from your end?

Thanks to @Yug-Mistry.

**Comment by ankitpanwar070798** [comment]
@hari yeah now working fine.

**Comment by hari** [comment]
Thank you @ankitpanwar070798 and @Yug-Mistry for your contributions.
