### ISSUE TITLE
The icons gets hover effect at wrong place

### ISSUE THREAD

**Issue by Yug-Mistry** [codse/animata#183]
**Describe the bug**
The effect which needs to be triggered on hover on text gets triggered on icons also.

**To Reproduce**
1. Go to 'https://animata.design/docs/hero/hero-section-text-hover'
2. Hover on 'icon where it is supposed to before animation'
3. See error

**Expected behavior**
The effect should only get triggered when text is hovered.

**Screenshots**
![image](https://github.com/user-attachments/assets/1fb5a3f1-6a2b-418b-b68e-05b5706eacbf)

**Comment by Yug-Mistry** [comment]
working on it

**Comment by hari** [comment]
Feel free to enhance this component, @Yug-Mistry. You have the opportunity to make it even better. Check out the reference here: https://www.figma.com/community

**Discover community-made libraries, icon sets, and more** section

**Comment by hari** [comment]
Closed by #184 

Thank you @Yug-Mistry for your contribution.
