### ISSUE TITLE
Text Reveal on scroll

### ISSUE THREAD

**Issue by gusmagnago** [codse/animata#186]
**Is your feature request related to a problem? Please describe.**
It's not related to a problem, but I couldn't find the solution for a text reveal when scrolling, not a free version of it.

**Describe the solution you'd like**
It should reveal text by scrolling, so each word should be displayed one by one during the scroll, and when the text finishes, it should scroll normally the page again.

**Describe alternatives you've considered**
I considered using GSAP Split Text, but I can't afford it. Also, I couldn't achieve this goal with framer-motion.

**Additional context**

https://github.com/user-attachments/assets/5875f9b2-8b71-488f-b02c-eac641355e67
This is a video I took from the Saas company: https://www.onassemble.com/

**Comment by hari** [comment]
@gusmagnago it is available now: https://animata.design/docs/text/scroll-reveal
