### ISSUE TITLE
Feature card - 005 [Survey]

### ISSUE THREAD

**Issue by sudhashrestha** [codse/animata#220]
### Description
Create the feature card component as shown in the video attached below.

### Animation Preview
- Screenshot/Video: 

https://github.com/user-attachments/assets/96e1d217-0d06-4759-bcb1-27dd9ace7df5

> [!NOTE]
> Please refer to the **Animata contributing guidelines** available [here](https://www.animata.design/docs/contributing) for rules on how to contribute to the project. Let us know in the comments if you’re working on this issue, and feel free to ask any questions!

### Requirements
- [ ] Create a new animated component that matches the provided design.
- [ ] Add example usage of the component in the documentation or storybook.

<details>
  <summary>
    <h3> Guidelines & Best Practices</h3>
  </summary>

- Write reusable and clean code following the project’s style guide.
- The component should be **fully customizable**. The user should be able to modify props such as duration, easing, color, and size where applicable.
- Follow the [Contributing Guidelines](https://www.animata.design/docs/contributing) before submitting your pull request.

</details>

> [!IMPORTANT]  
> To ensure more contributors have the opportunity to participate, we kindly request that:
> - Each contributor submits only **one pull request** related to this issue.
> - If you're interested in working on this issue, first check if it has already been claimed. If not, **assign yourself** to the issue and move it to **In Progress** on the project board.

---
### Checklist
- [ ] I have read and followed the contributing guidelines.
- [ ] I have developed the component according to the requirements.
- [ ] I have tested the component across different browsers and screen sizes.
- [ ] I have documented the component for future reference.
- [ ] I have submitted a pull request with appropriate labels and referenced this issue number.

**Comment by mohitahlawat2001** [comment]
i want to work on this issue , please assign it to me
have some question in mind , 

- for styling what we have to use , 
- we have to make normal react component , 
- for data i need to add psudo data,

in below picture 
![image](https://github.com/user-attachments/assets/48af6ed7-c022-4f85-9020-be47a1016f52)
_name written on right side are button which is used to collect data 
left side bar shows how many people selected that button
name on top is questoin of survey _ 
or there meaning is something else you can also tell
