### ISSUE TITLE
Feature card - 008 [Webhook]

### ISSUE THREAD

**Issue by sudhashrestha** [codse/animata#223]
### Description
Create the feature card component as shown in the video attached below.

### Animation Preview
- Screenshot/Video: 

https://github.com/user-attachments/assets/bd168e42-5b0c-4d4c-9f36-4fe96461555c

> [!NOTE]
> Please refer to the **Animata contributing guidelines** available [here](https://www.animata.design/docs/contributing) for rules on how to contribute to the project. Let us know in the comments if you’re working on this issue, and feel free to ask any questions!

### Requirements
- [ ] Create a new animated component that matches the provided design.
- [ ] Add example usage of the component in the documentation or storybook.

<details>
  <summary>
    <h3> Guidelines & Best Practices</h3>
  </summary>

- Write reusable and clean code following the project’s style guide.
- The component should be **fully customizable**. The user should be able to modify props such as duration, easing, color, and size where applicable.
- Follow the [Contributing Guidelines](https://www.animata.design/docs/contributing) before submitting your pull request.

</details>

> [!IMPORTANT]  
> To ensure more contributors have the opportunity to participate, we kindly request that:
> - Each contributor submits only **one pull request** related to this issue.
> - If you're interested in working on this issue, first check if it has already been claimed. If not, **assign yourself** to the issue and move it to **In Progress** on the project board.

---
### Checklist
- [ ] I have read and followed the contributing guidelines.
- [ ] I have developed the component according to the requirements.
- [ ] I have tested the component across different browsers and screen sizes.
- [ ] I have documented the component for future reference.
- [ ] I have submitted a pull request with appropriate labels and referenced this issue number.

**Comment by Pavankumar07s** [comment]
hey @sudhashrestha i want to make this Feature card 😊

**Comment by sudhashrestha** [comment]
@Anushlinux 


I am assigning this to @Pavankumar07s using first come first serve

**Comment by Anushlinux** [comment]
> @Anushlinux I have created the component ,can you have a look on this.
> 
> https://github.com/user-attachments/assets/b4454b80-ed9a-46c2-8977-a796ff5f31e5
> 
> 

Looks nice any other design feature you wanna add let me know
