### ISSUE TITLE
Feature card - 009 [Automation]

### ISSUE THREAD

**Issue by sudhashrestha** [codse/animata#224]
### Description
Create the feature card component as shown in the video attached below.

### Animation Preview
- Screenshot/Video: 

https://github.com/user-attachments/assets/3a3c192a-e268-4342-80e1-f4624c3e3b13

> [!NOTE]
> Please refer to the **Animata contributing guidelines** available [here](https://www.animata.design/docs/contributing) for rules on how to contribute to the project. Let us know in the comments if you’re working on this issue, and feel free to ask any questions!

### Requirements
- [ ] Create a new animated component that matches the provided design.
- [ ] Add example usage of the component in the documentation or storybook.

<details>
  <summary>
    <h3> Guidelines & Best Practices</h3>
  </summary>

- Write reusable and clean code following the project’s style guide.
- The component should be **fully customizable**. The user should be able to modify props such as duration, easing, color, and size where applicable.
- Follow the [Contributing Guidelines](https://www.animata.design/docs/contributing) before submitting your pull request.

</details>

> [!IMPORTANT]  
> To ensure more contributors have the opportunity to participate, we kindly request that:
> - Each contributor submits only **one pull request** related to this issue.
> - If you're interested in working on this issue, first check if it has already been claimed. If not, **assign yourself** to the issue and move it to **In Progress** on the project board.

---
### Checklist
- [ ] I have read and followed the contributing guidelines.
- [ ] I have developed the component according to the requirements.
- [ ] I have tested the component across different browsers and screen sizes.
- [ ] I have documented the component for future reference.
- [ ] I have submitted a pull request with appropriate labels and referenced this issue number.

**Comment by vishal-kumar3** [comment]
Hey can you assign this issue to me, i want to work on this.

**Comment by 10kumaranurag01** [comment]
Hey @sudhashrestha , I can develop this feature, can you please assign it to me?

**Comment by sudhashrestha** [comment]
@10kumaranurag01 

@vishal-kumar3 has already requested it so I am assigning this to him using first come first serve basis.

**Comment by 10kumaranurag01** [comment]
Ohk looking forward to new features or bugs to contribute @sudhashrestha

**Comment by sudhashrestha** [comment]
@10kumaranurag01 Sure, I am going to add lots of new tickets today.

**Comment by 10kumaranurag01** [comment]
Looking forward to it @sudhashrestha

**Comment by vishal-kumar3** [comment]
Getting this error on every page, can you please help me solve this

![Screenshot from 2024-10-01 18-46-21](https://github.com/user-attachments/assets/16552c41-039f-4853-a84c-80dc3d9e8c24)
![Screenshot from 2024-10-01 18-41-37](https://github.com/user-attachments/assets/72c23051-3ac5-4067-b732-ae8e93d570bb)

**Comment by hari** [comment]
@vishal-kumar3 Could you join discord and message there? https://discord.gg/YfvqMf5MTE

**Comment by vishal-kumar3** [comment]
> @vishal-kumar3 Could you join discord and message there? https://discord.gg/YfvqMf5MTE

i have messaged in your discord channel.

**Comment by vishal-kumar3** [comment]
hey @sudhashrestha, i have created a PR for this issue and attached a video of the animation component. Please go through it and if there is something you want me to change or refine then tell me.
