### ISSUE TITLE
Orbiting items (3D)

### ISSUE THREAD

**Issue by sudhashrestha** [codse/animata#226]
### Description
Create the component as shown in the video attached below. We already have an [orbiting items component](https://animata.design/docs/list/orbiting-items) as this one, but this is more complex and 3d looking.

### Animation Preview
- Screenshot/Video:

https://github.com/user-attachments/assets/5ba932d2-b669-4190-93db-bd62c661b479

> [!NOTE]
> Please refer to the **Animata contributing guidelines** available [here](https://www.animata.design/docs/contributing) for rules on how to contribute to the project. Let us know in the comments if you’re working on this issue, and feel free to ask any questions!

### Requirements
- [ ] Create a new animated component that matches the provided design.
- [ ] Add example usage of the component in the documentation or storybook.

<details>
  <summary>
    <h3> Guidelines & Best Practices</h3>
  </summary>

- Write reusable and clean code following the project’s style guide.
- The component should be **fully customizable**. The user should be able to modify props such as duration, easing, color, and size where applicable.
- Follow the [Contributing Guidelines](https://www.animata.design/docs/contributing) before submitting your pull request.

</details>

> [!IMPORTANT]  
> To ensure more contributors have the opportunity to participate, we kindly request that:
> - Each contributor submits only **one pull request** related to this issue.
> - If you're interested in working on this issue, first check if it has already been claimed. If not, **assign yourself** to the issue and move it to **In Progress** on the project board.

### Additional resources
Posted on X by: https://x.com/oguzyagizkara/status/1699745310312960219

---
### Checklist
- [ ] I have read and followed the contributing guidelines.
- [ ] I have developed the component according to the requirements.
- [ ] I have tested the component across different browsers and screen sizes.
- [ ] I have documented the component for future reference.
- [ ] I have submitted a pull request with appropriate labels and referenced this issue number.

**Comment by evgongora** [comment]
Hello my name is Erick! I'm a web development student from Costa Rica starting to make contributions to OSS projects Web3/Web2, I would love to contribute to this project I have experience working with TS/Next.js/React and Tailwind. 
You can check my OD profile https://app.onlydust.com/u/evgongora

Looking forward to work on this! :)

**Comment by Pikachu-345** [comment]
hey @sudhashrestha can you please share the icons image in the referred video..
Would love to work on this

**Comment by sudhashrestha** [comment]
@Pikachu-345 You don't need to use those exact icons. You can just use lucide-react for this.

**Comment by sudhashrestha** [comment]
@evgongora You have another ticket assigned already so I'm assigning this one to @Pikachu-345

**Comment by Pikachu-345** [comment]
@sudhashrestha  does this org has any slack or discord server where we can discuss issues ? 
Cause there are some question about this issue..

**Comment by hari** [comment]
@Pikachu-345 here's the discord link: https://discord.gg/YfvqMf5MTE

**Comment by Pikachu-345** [comment]
Hey @sudhashrestha  @hari have created a PR #243 please review and suggest changes if required
