### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by preronagit** [codse/animata#229]
Add Code of Conduct.md file to this repo

**Comment by preronagit** [comment]
@hari I would like to work on this issue. Please assign it to me under hacktoberfest.

**Comment by hari** [comment]
@preronagit sure

**Comment by preronagit** [comment]
@hari Can you please assign this issue to me?

**Comment by preronagit** [comment]
@hari Sir, I have opened a pull request. Can u kindly label this issue under hacktoberfest?

**Comment by hari** [comment]
@preronagit sure
