### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by yashksaini-coder** [codse/animata#231]
**Is your feature request related to a problem? Please describe.**  
The README lacks clear instructions and details, making it difficult for new users to get started. 

**Describe the solution you'd like**  
Improve the README by adding:
- A project introduction and purpose.
- Detailed installation and setup steps.
- Usage examples and contributing guidelines.
- Visual aids like screenshots or diagrams.

**Describe alternatives you've considered**  
Linking to external documentation, but an enhanced README with all details would improve user experience.

**Additional context**  
Adding troubleshooting tips and badges for status/versioning could further improve clarity.

---

i would like to work on this issue so can you assign this issue to me & add labels to this issue. @hari

**Comment by hari** [comment]
@yashksaini-coder Thank you for the detailed ticket.

Have you checked the contributing section? https://animata.design/docs/contributing

If it is still confusing please feel free to improve it.

**Comment by mahaveergurjar** [comment]
@yashksaini-coder assign me

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder Thank you for the detailed ticket.
> 
> Have you checked the contributing section? https://animata.design/docs/contributing
> 
> If it is still confusing please feel free to improve it.

@hari I would like to work on the docs to improve & add a smooth transition effect when user click on the index.
How does that sounds ?

**Comment by hari** [comment]
Sounds good @yashksaini-coder
