### ISSUE TITLE
Improved Newsletter Component

### ISSUE THREAD

**Issue by SatyamVyas04** [codse/animata#234]
**Is your feature request related to a problem? Please describe.**
The newsletter input is difficult to distinguish from the rest of the website on various browsers. It appears small and lacks a clear call-to-action, impacting its visibility and usability.

**Describe the solution you'd like**
Implement a card component wrapper for the newsletter and adjust margins and padding to enhance readability and visual prominence.

**Describe alternatives you've considered**
An alternative approach would be to maintain the current website layout while increasing the size of the newsletter input field.

**Additional context**
I have made improvements locally and can submit a pull request once the issue is assigned and the proposed changes are approved. For reference, I've included a comparison of the current and improved versions.

---

![image](https://github.com/user-attachments/assets/c19d6fc1-7cce-44c4-bb90-5cef56447837)
![image](https://github.com/user-attachments/assets/93026759-1a8a-4057-971b-482b6dd1188a)

**Comment by hari** [comment]
@SatyamVyas04 looks good to me!

**Comment by SatyamVyas04** [comment]
Closing this issue, since the PR was merged!
