### ISSUE TITLE
Interactive case study card

### ISSUE THREAD

**Issue by sudhashrestha** [codse/animata#242]
### Description
Create the interactive case study card component as shown in the video attached below. 

### Animation Preview
- Screenshot/Video: 

https://github.com/user-attachments/assets/3f87d6f0-4a92-4011-8c23-86f89a3e06b2

> [!NOTE]
> Please refer to the **Animata contributing guidelines** available [here](https://www.animata.design/docs/contributing) for rules on how to contribute to the project. Let us know in the comments if you’re working on this issue, and feel free to ask any questions!

### Requirements
- [ ] Create a new animated component that matches the provided design.
- [ ] Add example usage of the component in the documentation or storybook.

<details>
  <summary>
    <h3> Guidelines & Best Practices</h3>
  </summary>

- Write reusable and clean code following the project’s style guide.
- The component should be **fully customizable**. The user should be able to modify props such as duration, easing, color, and size where applicable.
- Follow the [Contributing Guidelines](https://www.animata.design/docs/contributing) before submitting your pull request.

</details>

> [!IMPORTANT]  
> To ensure more contributors have the opportunity to participate, we kindly request that:
> - Each contributor submits only **one pull request** related to this issue.
> - If you're interested in working on this issue, first check if it has already been claimed. If not, **assign yourself** to the issue and move it to **In Progress** on the project board.

### Additional resources
Posted on X by: https://x.com/RomaTesla/status/1683429296939888640

---
### Checklist
- [ ] I have read and followed the contributing guidelines.
- [ ] I have developed the component according to the requirements.
- [ ] I have tested the component across different browsers and screen sizes.
- [ ] I have documented the component for future reference.
- [ ] I have submitted a pull request with appropriate labels and referenced this issue number.

**Comment by webdevNYC** [comment]
Hey there, can you assign it to me?  I want to start to collaborate. :o)

**Comment by webdevNYC** [comment]
Hi there, I have the interaction code working. I'm just not sure about the content for each card. Right now, I'm passing just the children and giving total control to the children for the cover. Is that what you're looking for? If you need to have a component with parameters (which ones?), please let me know, and maybe we can maybe create another ticket for it.  

https://github.com/webdevNYC/animata/tree/af-case-study-card
