### ISSUE TITLE
Site preloader - Vertical tiles

### ISSUE THREAD

**Issue by sudhashrestha** [codse/animata#249]
### Description
Create the site preloader component as shown in the video attached below. Please note that you will need to build the loader (vertical tiles), not the actual content that is shown in the video. Make sure that the loader is fully responsive

### Animation Preview
- Screenshot/Video: 

https://github.com/user-attachments/assets/add2c6d1-ae0f-4c0f-9137-bea5794420f5

> [!NOTE]  
> Please refer to the **Animata contributing guidelines** available [here](https://www.animata.design/docs/contributing) for rules on how to contribute to the project. Let us know in the comments if you’re working on this issue, and feel free to ask any questions!

### Requirements
1. Create a new animated component that matches the provided design.
2. Add example usage of the component in the documentation or storybook.

<details>
  <summary>
    <h3> Guidelines & Best Practices</h3>
  </summary>

- Write reusable and clean code following the project’s style guide.
- The component should be **fully customizable**. The user should be able to modify props such as duration, easing, color, and size where applicable.
- Follow the [Contributing Guidelines](https://www.animata.design/docs/contributing) before submitting your pull request.

</details>

> [!IMPORTANT]  
> To ensure more contributors have the opportunity to participate, we kindly request that:
> - Each contributor submits only **one pull request** related to this issue.
> - If you're interested in working on this issue, please comment below. We will assign the issue on a **first-come, first-served basis**.

---

### Additional Resources
Referenced from: [www.steviaplease.me](https://www.steviaplease.me/)

**Comment by SatyamVyas04** [comment]
I'd like to volunteer. Please assign me this feat. @sudhashrestha

**Comment by SatyamVyas04** [comment]
I wanted to confirm the desired file structure for this feature. Based on the initial description, I'm assuming it should look something like this:

```plaintext
animata/
    background/
    bento/
    ...
    preloader/
        vertical-tiles.tsx
```

Could you please confirm if this is correct? Specifically, I need to understand where the `vertical-tiles.tsx` preloader should be placed.

Thanks in advance for the clarification! 😊

**Comment by sudhashrestha** [comment]
Hi @SatyamVyas04 You can use our script `yarn animata:new` to create a new component. This will automatically handle which folder the component should be put into. If there's no type called "preloader" you can create one. For more info: https://animata.design/docs/contributing/components
