### ISSUE TITLE
Notification message - with user info

### ISSUE THREAD

**Issue by sudhashrestha** [codse/animata#256]
### Description
Create the component as shown in the video attached below.

### Animation Preview
- Screenshot/Video:

https://github.com/user-attachments/assets/1e8c07e5-a2c7-43db-9b39-f90f1e7a7f6c

> [!NOTE]  
> Please refer to the **Animata contributing guidelines** available [here](https://www.animata.design/docs/contributing) for rules on how to contribute to the project. Let us know in the comments if you’re working on this issue, and feel free to ask any questions!

### Requirements
1. Create a new animated component that matches the provided design.
2. Add example usage of the component in the documentation or storybook.

<details>
  <summary>
    <h3> Guidelines & Best Practices</h3>
  </summary>

- Write reusable and clean code following the project’s style guide.
- The component should be **fully customizable**. The user should be able to modify props such as duration, easing, color, and size where applicable.
- Follow the [Contributing Guidelines](https://www.animata.design/docs/contributing) before submitting your pull request.

</details>

> [!IMPORTANT]  
> To ensure more contributors have the opportunity to participate, we kindly request that:
> - Each contributor submits only **one pull request** related to this issue.
> - If you're interested in working on this issue, please comment below. We will assign the issue on a **first-come, first-served basis**.

---

### Additional Resources
Posted on X by: https://x.com/bartek_marzec/status/1838681304814227461

---

> [!Tip]
> Join our Discord community if you need help or have any questions. We're here to help you get started and guide you through the process. [Join now](https://discord.gg/YfvqMf5MTE)

**Comment by bandhan-majumder** [comment]
I would like to work on this. Can u assign this issue to me?

**Comment by sudhashrestha** [comment]
@bandhan-majumder Assigned.

**Comment by bandhan-majumder** [comment]
Just a quick question. I know that creating a new branch before making any changes is considered as best practice. But I am a bit confused as `running-locally.mdx` doesn't contain that step and neither I am able to see multiple branches.

**Comment by sudhashrestha** [comment]
@bandhan-majumder You should fork the repo first. Then, submit a pull request when you're ready.

**Comment by bandhan-majumder** [comment]
Sorry if my question was confusing. I am asking after forking, I should create my own branch where my changes will reflect without disturbing the `main` right?

**Comment by sudhashrestha** [comment]
@bandhan-majumder  There's no need to create a new branch in your fork. You can if you want, but that's not necessary.

**Comment by bandhan-majumder** [comment]
Hey I have opened a pull request regarding this issue. Can you please review it?
