### ISSUE TITLE
Music stack interaction

### ISSUE THREAD

**Issue by sudhashrestha** [codse/animata#273]
### Description
Create the component as shown in the video attached below.

### Animation Preview
- Screenshot/Video:

https://github.com/user-attachments/assets/e6208437-4712-4a02-866f-40a5b66524d6

> [!NOTE]  
> Please refer to the **Animata contributing guidelines** available [here](https://www.animata.design/docs/contributing) for rules on how to contribute to the project. Let us know in the comments if you’re working on this issue, and feel free to ask any questions!

### Requirements
1. Create a new animated component that matches the provided design.
2. Add example usage of the component in the documentation or storybook.

<details>
  <summary>
    <h3> Guidelines & Best Practices</h3>
  </summary>

- Write reusable and clean code following the project’s style guide.
- The component should be **fully customizable**. The user should be able to modify props such as duration, easing, color, and size where applicable.
- Follow the [Contributing Guidelines](https://www.animata.design/docs/contributing) before submitting your pull request.

</details>

> [!IMPORTANT]  
> To ensure more contributors have the opportunity to participate, we kindly request that:
> - Each contributor submits only **one pull request** related to this issue.
> - If you're interested in working on this issue, please comment below. We will assign the issue on a **first-come, first-served basis**.

---

### Additional Resources
Posted on X by: https://x.com/prathamux/status/1830695803184390438

---

> [!Tip]
> Join our Discord community if you need help or have any questions. We're here to help you get started and guide you through the process. [Join now](https://discord.gg/YfvqMf5MTE)

**Comment by mohitahlawat2001** [comment]
I want to work on  this issue, please assign me .

**Comment by ShoomanKhatri** [comment]
Cant we do it without assigning??

**Comment by sudhashrestha** [comment]
@ShoomanKhatri two people might work on same thing without assigning.

**Comment by mohitahlawat2001** [comment]
@sudhashrestha can you tell type of component ?

**Comment by hari** [comment]
@mohitahlawat2001 it is a "widget"
