### ISSUE TITLE
Remote team clock

### ISSUE THREAD

**Issue by sudhashrestha** [codse/animata#294]
### Description
Create the component as shown in the video attached below.

### Animation Preview
- Screenshot/Video:

https://github.com/user-attachments/assets/c6a218ef-9b09-44aa-9bc5-24f80860c041

> [!NOTE]  
> Please refer to the **Animata contributing guidelines** available [here](https://www.animata.design/docs/contributing) for rules on how to contribute to the project. Let us know in the comments if you’re working on this issue, and feel free to ask any questions!

### Requirements
1. Create a new animated component that matches the provided design.
2. Add example usage of the component in the documentation or storybook.

<details>
  <summary>
    <h3> Guidelines & Best Practices</h3>
  </summary>

- Write reusable and clean code following the project’s style guide.
- The component should be **fully customizable**. The user should be able to modify props such as duration, easing, color, and size where applicable.
- Follow the [Contributing Guidelines](https://www.animata.design/docs/contributing) before submitting your pull request.

</details>

> [!IMPORTANT]  
> To ensure more contributors have the opportunity to participate, we kindly request that:
> - Each contributor submits only **one pull request** related to this issue.
> - If you're interested in working on this issue, please comment below. We will assign the issue on a **first-come, first-served basis**.

---

### Additional Resources
Posted on X by: https://x.com/KumailNanji/status/1821162391419093017

---

> [!Tip]
> Join our Discord community if you need help or have any questions. We're here to help you get started and guide you through the process. [Join now](https://discord.gg/YfvqMf5MTE)

**Comment by ShoomanKhatri** [comment]
plz assign this to me..

**Comment by sudhashrestha** [comment]
@ShoomanKhatri  Sure, I will assign it once you're done with your other issues. In the meantime, this will remain unassigned for other contributors.

**Comment by nooras** [comment]
Hie @ShoomanKhatri 
Can i take this task ? can you provide any reference?

**Comment by ArjunCodess** [comment]
Hey, can I be assigned this task? I already have the PR finished with me.

**Comment by TarushGupta23** [comment]
i would like to take part in this!!!

**Comment by ArjunCodess** [comment]
Hey @sudhashrestha,

I’ve created the PR: https://github.com/codse/animata/pull/368.
Please review it and let me know if any changes are needed. Looking forward to your feedback.
