### ISSUE TITLE
Button with hover animation

### ISSUE THREAD

**Issue by sudhashrestha** [codse/animata#300]
### Description
Create the component as shown in the video attached below.

### Animation Preview
- Screenshot/Video:

https://github.com/user-attachments/assets/aa36dcdf-7b55-4038-a714-135053a4d3c3

> [!NOTE]  
> Please refer to the **Animata contributing guidelines** available [here](https://www.animata.design/docs/contributing) for rules on how to contribute to the project. Let us know in the comments if you’re working on this issue, and feel free to ask any questions!

### Requirements
1. Create a new animated component that matches the provided design.
2. Add example usage of the component in the documentation or storybook.

<details>
  <summary>
    <h3> Guidelines & Best Practices</h3>
  </summary>

- Write reusable and clean code following the project’s style guide.
- The component should be **fully customizable**. The user should be able to modify props such as duration, easing, color, and size where applicable.
- Follow the [Contributing Guidelines](https://www.animata.design/docs/contributing) before submitting your pull request.

</details>

> [!IMPORTANT]  
> To ensure more contributors have the opportunity to participate, we kindly request that:
> - Each contributor submits only **one pull request** related to this issue.
> - If you're interested in working on this issue, please comment below. We will assign the issue on a **first-come, first-served basis**.

---

### Additional Resources
Posted on X by: https://x.com/codebydennis/status/1832041073897578894

---

> [!Tip]
> Join our Discord community if you need help or have any questions. We're here to help you get started and guide you through the process. [Join now](https://discord.gg/YfvqMf5MTE)

**Comment by AE-Hertz** [comment]
@sudhashrestha pls assign this task to me

**Comment by ShoomanKhatri** [comment]
me too.

**Comment by sudhashrestha** [comment]
Hey @AE-Hertz @ShoomanKhatri We're only assigning one ticket per person at this time. Please submit a PR for one of your assigned tickets and let me know. I am keeping this unassigned for other contributors. Thanks

**Comment by hari** [comment]
@AE-Hertz I will review your portfolio PR today. We will probably move it to a different repo as it is a template that the user can clone, edit, and deploy.

In the meantime, I have assigned you this one.

**Comment by AE-Hertz** [comment]
@hari okay, let me know you if i can help with anything or give me location i will send PR their , 
meanwhile i am looking into this issue. Thanks

**Comment by AE-Hertz** [comment]
Update :  @hari @sudhashrestha  I am done making this component, I will request for PR tomorrow. 
But I was really looking for existing PR #293  to be merged, as it acts as motivation. Thank you.
