### ISSUE TITLE
FAQ Section

### ISSUE THREAD

**Issue by sudhashrestha** [codse/animata#307]
### Description
Create the component as shown in the video attached below.

### Animation Preview
- Screenshot/Video:

https://github.com/user-attachments/assets/cf8af2a5-c9e7-4b2e-a7c6-4e2fc910d185

> [!NOTE]  
> Please refer to the **Animata contributing guidelines** available [here](https://www.animata.design/docs/contributing) for rules on how to contribute to the project. Let us know in the comments if you’re working on this issue, and feel free to ask any questions!

### Requirements
1. Create a new animated component that matches the provided design.
2. Add example usage of the component in the documentation or storybook.

<details>
  <summary>
    <h3> Guidelines & Best Practices</h3>
  </summary>

- Write reusable and clean code following the project’s style guide.
- The component should be **fully customizable**. The user should be able to modify props such as duration, easing, color, and size where applicable.
- Follow the [Contributing Guidelines](https://www.animata.design/docs/contributing) before submitting your pull request.

</details>

> [!IMPORTANT]  
> To ensure more contributors have the opportunity to participate, we kindly request that:
> - Each contributor submits only **one pull request** related to this issue.
> - If you're interested in working on this issue, please comment below. We will assign the issue on a **first-come, first-served basis**.

---

### Additional Resources
Posted on X by: https://x.com/FonsMans/status/1824582565279436925

---

> [!Tip]
> Join our Discord community if you need help or have any questions. We're here to help you get started and guide you through the process. [Join now](https://discord.gg/YfvqMf5MTE)

**Comment by CBID2** [comment]
Can I be assigned to this @hari? I don’t see a PR created for this issue

**Comment by hari** [comment]
@anshuman008 are you working on this? If not I can assign this to @CBID2

**Comment by sudhashrestha** [comment]
Hi @anshuman008 

I hope you're doing well! Since it's been a while since this issue was assigned, I wanted to check in and see if you're still planning to work on it. If so, could you kindly share an update by tomorrow?

If I don't hear back by then, I’ll unassign the issue to allow others to take it up.

Thanks for your understanding!

**Comment by CBID2** [comment]
> Hi @anshuman008
> 
> I hope you're doing well! Since it's been a while since this issue was assigned, I wanted to check in and see if you're still planning to work on it. If so, could you kindly share an update by tomorrow?
> 
> If I don't hear back by then, I’ll unassign the issue to allow others to take it up.
> 
> Thanks for your understanding!

Can you assign it to me @anshuman008? I asked recently

**Comment by sudhashrestha** [comment]
@CBID2 Hacktoberfest is ending soon, so if possible please try to complete it before the end of October. Thanks.

**Comment by CBID2** [comment]
Hey @sudhashrestha. I want to work on [this issue](https://github.com/codse/animata/issues/215) instead

**Comment by masabinhok** [comment]
I will give it a try.

**Comment by masabinhok** [comment]
I've made a modified version of the original to ensure it has a unique feel. Which one do you think we should go with? If you have any suggestions for changes, please let me know!

https://github.com/user-attachments/assets/b64c5201-0fbe-4c01-a4b9-3c26b93f05cb

**Comment by anshuman008** [comment]
@hari @sudhashrestha @masabinhok Hey, this pr is already merged. check-> #348

**Comment by masabinhok** [comment]
No worries! If you'd like, I can update it, adjust the colors, add animations, and tilt the icons. I think those elements are currently missing.

**Comment by sudhashrestha** [comment]
@masabinhok Sure, you can update the existing one and create a PR. It looks like the issue was not linked to the PR which is already merged. Sorry for the confusion.
