### ISSUE TITLE
Content scan effect

### ISSUE THREAD

**Issue by sudhashrestha** [codse/animata#310]
### Description
Create the component as shown in the video attached below.

### Animation Preview
- Screenshot/Video:

https://github.com/user-attachments/assets/38d5e35d-7479-4e9d-887f-56f4216bb5cf

> [!NOTE]  
> Please refer to the **Animata contributing guidelines** available [here](https://www.animata.design/docs/contributing) for rules on how to contribute to the project. Let us know in the comments if you’re working on this issue, and feel free to ask any questions!

### Requirements
1. Create a new animated component that matches the provided design.
2. Add example usage of the component in the documentation or storybook.

<details>
  <summary>
    <h3> Guidelines & Best Practices</h3>
  </summary>

- Write reusable and clean code following the project’s style guide.
- The component should be **fully customizable**. The user should be able to modify props such as duration, easing, color, and size where applicable.
- Follow the [Contributing Guidelines](https://www.animata.design/docs/contributing) before submitting your pull request.

</details>

> [!IMPORTANT]  
> To ensure more contributors have the opportunity to participate, we kindly request that:
> - Each contributor submits only **one pull request** related to this issue.
> - If you're interested in working on this issue, please comment below. We will assign the issue on a **first-come, first-served basis**.

---

### Additional Resources
Posted on X by: https://x.com/SkenoxDesigns/status/1823082732291006533

---

> [!Tip]
> Join our Discord community if you need help or have any questions. We're here to help you get started and guide you through the process. [Join now](https://discord.gg/YfvqMf5MTE)

**Comment by bandhan-majumder** [comment]
Hey. I want some clarification on this issue. Do we have to create the text area component only where the selected words will be highlighted with that scanning effect? or the whole with the icons and the animated percentage text below?

**Comment by sudhashrestha** [comment]
@bandhan-majumder Sorry for the confusion. Only the input is required, but a button that would trigger the scanning effect would be great!

**Comment by asmit27rai** [comment]
@hari please assign it to me

**Comment by bandhan-majumder** [comment]
> @bandhan-majumder Sorry for the confusion. Only the input is required, but a button that would trigger the scanning effect would be great!

Thanks. Can u assign this issue to me?
