### ISSUE TITLE
Customizable speed dial with a tooltip

### ISSUE THREAD

**Issue by masabinhok** [codse/animata#316]
### Description
Create the component as shown in the video attached below.

### Animation Preview
- Screenshot/Video:

https://github.com/user-attachments/assets/66bff353-ff78-420f-95d4-01bd4588d272

> [!NOTE]  
> Please refer to the **Animata contributing guidelines** available [here](https://www.animata.design/docs/contributing) for rules on how to contribute to the project. Let us know in the comments if you’re working on this issue, and feel free to ask any questions!

### Requirements
1. Create a new animated component that matches the provided design.
2. Add example usage of the component in the documentation or storybook.

<details>
  <summary>
    <h3> Guidelines & Best Practices</h3>
  </summary>

- Write reusable and clean code following the project’s style guide.
- The component should be **fully customizable**. The user should be able to modify props such as duration, easing, color, and size where applicable.
- Follow the [Contributing Guidelines](https://www.animata.design/docs/contributing) before submitting your pull request.

</details>

> [!IMPORTANT]  
> To ensure more contributors have the opportunity to participate, we kindly request that:
> - Each contributor submits only **one pull request** related to this issue.
> - If you're interested in working on this issue, please comment below. We will assign the issue on a **first-come, first-served basis**.

### Reference 
https://mui.com/material-ui/react-speed-dial/#basic-speed-dial

---

> [!Tip]
> Join our Discord community if you need help or have any questions. We're here to help you get started and guide you through the process. [Join now](https://discord.gg/YfvqMf5MTE)

---

**Comment by masabinhok** [comment]
The video preview is the solution itself, if this component doesn't exist or isn't planned, I would love to contribute this component to animata.

**Comment by sudhashrestha** [comment]
@masabinhok Sure, please add references as well (if any). Thanks

**Comment by masabinhok** [comment]
Added. 
Preview is not working and i am getting some errors, i couln't resolve.
![image](https://github.com/user-attachments/assets/5f4422dc-f616-41a2-9e15-7e24391e1405)
![image](https://github.com/user-attachments/assets/0adb848e-8a39-4eb1-8b84-7ee5c370df84)
