### ISSUE TITLE
Arrow button

### ISSUE THREAD

**Issue by sudhashrestha** [codse/animata#317]
### Description
Create the component as shown in the video attached below.

### Animation Preview
- Screenshot/Video:

https://github.com/user-attachments/assets/15ea3188-e3c8-4375-92f4-f764dfedf945

> [!NOTE]  
> Please refer to the **Animata contributing guidelines** available [here](https://www.animata.design/docs/contributing) for rules on how to contribute to the project. Let us know in the comments if you’re working on this issue, and feel free to ask any questions!

### Requirements
1. Create a new animated component that matches the provided design.
2. Add example usage of the component in the documentation or storybook.

<details>
  <summary>
    <h3> Guidelines & Best Practices</h3>
  </summary>

- Write reusable and clean code following the project’s style guide.
- The component should be **fully customizable**. The user should be able to modify props such as duration, easing, color, and size where applicable.
- Follow the [Contributing Guidelines](https://www.animata.design/docs/contributing) before submitting your pull request.

</details>

> [!IMPORTANT]  
> To ensure more contributors have the opportunity to participate, we kindly request that:
> - Each contributor submits only **one pull request** related to this issue.
> - If you're interested in working on this issue, please comment below. We will assign the issue on a **first-come, first-served basis**.

---

### Additional Resources
Referenced from: https://astronote.framer.website/

---

> [!Tip]
> Join our Discord community if you need help or have any questions. We're here to help you get started and guide you through the process. [Join now](https://discord.gg/YfvqMf5MTE)

**Comment by wolfofdalalst** [comment]
Hello @sudhashrestha , can you please assign this issue to me?

**Comment by sudhashrestha** [comment]
@wolfofdalalst Done

**Comment by knight-95** [comment]
Hi @sudhashrestha , I would like to work on this

**Comment by vaishnav-3** [comment]
hey  @sudhashrestha  can i work on this

**Comment by ArjunCodess** [comment]
As it has already been a week, can I be assigned this issue? I can push the PR in two days.

**Comment by wolfofdalalst** [comment]
I am actively working on this issue. Due to some family emergency i was unable to work on it last week. I will complete this within this week. Please consider.

**Comment by ArjunCodess** [comment]
Oh, it's no problem. I just thought you forgot about it.

I hope everyone in your family is well and praying for the same. Take care.

**Comment by wolfofdalalst** [comment]
Hey @sudhashrestha,

I’ve created PR #369. Please review it and let me know if any changes are needed. Looking forward to your feedback.
